# Generated by Django 4.0.4 on 2022-06-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
